# Generated by Django 3.2.9 on 2021-12-07 20:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format (should be: 00xxxxxx)', regex='^[a-zA-Z]{2}\\d{6}$')], verbose_name='Booking_Number')),
                ('city', models.IntegerField(choices=[(1, 'Rome'), (2, 'Nice'), (3, 'Berlin')], verbose_name='City')),
                ('checkin_datetime', models.DateField(verbose_name='Checkin_Datetime')),
                ('checkout_datetime', models.DateField(verbose_name='Checkout_Datetime')),
                ('guest_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed in name', regex='^[a-zA-Z]{2,}$')], verbose_name='Guest_Name')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
