# Generated by Django 3.2.9 on 2021-12-01 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Booking_Number')),
                ('city', models.IntegerField(choices=[(1, 'Rome'), (2, 'Nice'), (3, 'Berlin')], verbose_name='City')),
                ('checkin_datetime', models.DateField(verbose_name='Checkin_Datetime')),
                ('checkout_datetime', models.DateField(verbose_name='Checkout_Datetime')),
                ('guest_name', models.TextField(max_length=20, verbose_name='Guest_Name')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
