# Generated by Django 3.2.9 on 2021-12-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='guest_name',
            field=models.CharField(max_length=20, verbose_name='Guest_Name'),
        ),
    ]
