# Generated by Django 3.2.9 on 2021-12-01 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='booking_number',
            field=models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format (00xxxxxx)', regex='^[a-zA-Z]{2}\\d{6}$')], verbose_name='Booking_Number'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='guest_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed in name', regex='^[a-zA-Z]{2,}$')], verbose_name='Guest_Name'),
        ),
    ]
