# Generated by Django 3.2.9 on 2021-12-01 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20211201_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='booking_number',
            field=models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format (should be: 00xxxxxx)', regex='^[a-zA-Z]{2}\\d{6}$')], verbose_name='Booking_Number'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Price'),
        ),
    ]
